### ISSUE TITLE
Different checksum for Win and Unix systems

### ISSUE THREAD

**Issue by Dani216** [grails-guides/grails-database-migration#1]
Hi everyone,

in our company we use Mac OS and Windows. When we run migration on Mac everything is working fine, but when we try to run the same migration on Win systems we getting different `checksum` for some files. These files contains UTF-8 characters e.g.: **á**, but in log file we can see **Ăˇ** char instead (**Jan Donátek** => **Jan DonĂˇtek**).

Stack trace Windows:
[stact-trace.txt](https://github.com/grails-guides/grails-database-migration/files/1547640/stact-trace.txt)

Is there any solutions how to solve this problem, other then rewrite these files?

Thanks,
Dan

**Comment by niravassar** [comment]
Hi Dan, thanks for using the guide. I hope it helped.

I believe this issue is strictly a Ascii problem between win and mac os, and the database migration plugin is adversely affected by it.  I dont think it is a java/grails issue. Nonetheless the issue still remains. Here is how I would approach the issue - i dont have solutions but would offer suggestions.

- A bandaid problem may be to run a manual script to change the databasechangelog table with the needed characters. OR change the name used to something else somehow with a windows login. I dont think this is a permanent solution.
- try testing out with different databases on local. with mysql you can create schemas with different UTF-8 standards, i dont know the variations by heart but this may make a differerence. See if the problem persists with different databases run on OS and Win.
- ensure the problem is becuase of different OS's. Does this occur on two different MAC computer or two separate Win Pcs?
- research ascii differences on OS - meaning is there a win registry setting that will resolve differences, thinking of the issue entirely separately than within the grails context
- explore the option of running the grails db migration plugin on cygwin under a lunix shell, does this make a difference?
